inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/RequireOrder:
  Enabled: true

Style/SafeNavigationChainLength:
  Enabled: false
